#!/bin/bash

TREE="$1"

# Use binutils-s390x-linux-gnu if present, otherwise local objdump
if [[ -e /usr/s390x-linux-gnu/bin/objdump ]] ; then
	OBJDUMP=/usr/s390x-linux-gnu/bin/objdump
else
	OBJDUMP=$(which objdump)
fi

# Run over the entire tree
for obj in $(find "$TREE" -name '*.o'); do

	# file and directory patterns to ignore
	if [[ "$obj" =~ .tmp_kallsyms*.o ]] ||
	   [[ "$obj" =~ vmlinux.o ]] ||
	   [[ "$obj" =~ built-in.o ]] ||
	   [[ "$obj" =~ \/arch/.*/boot\/ ]] ||
	   [[ "$obj" =~ \/scripts\/ ]] ||
	   [[ "$obj" =~ \/samples\/ ]] ; then
		continue
	fi

	$OBJDUMP -dr $obj | ./objtool.awk
done
